### ISSUE TITLE
panic: no active connection found: no Elasticsearch node available

### ISSUE THREAD

**Issue by b1ank1108** [fofapro/fapro#22]
报错：panic: no active connection found: no Elasticsearch node available

* ELK_VERSION=7.16.2
* docker

参考以下资料，添加了如下一堆还是没修改成功
https://stackoverflow.com/questions/61455272/cannot-connect-to-elastic-search-no-active-connection-found-no-elasticsearch
https://www.cnblogs.com/xiaoff/p/9913544.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html

```
cluster.name: "docker-cluster"
network.host: 0.0.0.0
http.host: 0.0.0.0
network.publish_host: 0.0.0.0
transport.host: 0.0.0.0
http.publish_port: 9200
```

**Comment by ntestoc3** [comment]
Please configure your elasticsearch like this:

https://raw.githubusercontent.com/fofapro/fapro/master/scripts/docker-compose.yml

```yaml 
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms2G -Xmx2G"
      network.publish_host: "127.0.0.1"
      ELASTIC_PASSWORD: "changeme"
      xpack.security.enabled: "true"
```
publish_host is your public IP address.
